# Site settings
title: 清泉古雾's Blog
email: jovex.xu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    关注前端技术，我可以做得更好！
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jser.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  JoveX
permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown
